"""Various constants that are unlikely to change."""

# BIT_TRANS: convert between the bit codes found in XML and the ones shown ingame.
bit_table = {'G': 'B',
             'R': 'A',
             'C': 'D',
             'B': 'C'}
BIT_TRANS = ''.maketrans(bit_table)

# ITEM_MOD_PROPS: difficulty and complexity changes when a mod is applied to an item
# ifcomplex means the change only applies if the item already has complexity > 0
# these values live in code, usually in ApplyModification() method of the Mod's .cs file
ITEM_MOD_PROPS = {'ModCounterweighted': {'complexity': 1,
                                         'difficulty': 1,
                                         'ifcomplex': True,
                                         'prefix': '&ycounterweighted '},
                  'ModElectrified': {'complexity': 1,
                                     'difficulty': 1,
                                     'ifcomplex': False,
                                     'prefix': '&Welectrified&y '},
                  'ModEngraved': {'complexity': 0,
                                  'difficulty': 0,
                                  'ifcomplex': False,
                                  'prefix': '&Ye&yn&cg&Cr&Ya&yv&ce&Cd &y'},
                  'ModExtradimensional': {'complexity': 4,
                                          'difficulty': 8,
                                          'ifcomplex': True,
                                          'prefix': '&Me&Mx&mt&mr&ya&yd&Yi&Ym&'
                                                    'Oe&Yn&Ys&yi&y&mo&mn&Ma&Ml&y '},
                  'ModFlaming': {'complexity': 1,
                                 'difficulty': 1,
                                 'ifcomplex': False,
                                 'prefix': '&Rflaming&y '},
                  'ModFreezing': {'complexity': 1,
                                  'difficulty': 1,
                                  'ifcomplex': False,
                                  'prefix': '&Cfreezing&y '},
                  'ModGesticulating': {'complexity': 1,
                                       'difficulty': 1,
                                       'ifcomplex': False,
                                       'prefix': '&mgesticulating &y'},
                  'ModGlassArmor': {'complexity': 0, 'difficulty': 0, 'ifcomplex': False},
                  'ModHeatSeeking': {'complexity': 1,
                                     'difficulty': 1,
                                     'ifcomplex': True,
                                     'prefix': '&yhoming '},
                  'ModImprovedElectricalGeneration': {'complexity': 0,
                                                      'difficulty': 0,
                                                      'ifcomplex': False},
                  'ModImprovedTemporalFugue': {'complexity': 0,
                                               'difficulty': 0,
                                               'ifcomplex': False},
                  'ModJewelEncrusted': {'complexity': 0, 'difficulty': 0, 'ifcomplex': False},
                  'ModMasterwork': {'complexity': 1,
                                    'difficulty': 1,
                                    'ifcomplex': True,
                                    'prefix': '&Ymasterwork&y '},
                  'ModPainted': {'complexity': 0,
                                 'difficulty': 0,
                                 'ifcomplex': False,
                                 'prefix': '&rp&Ra&Wi&wn&gt&Ge&Bd &y'},
                  'ModPiping': {'complexity': 0,
                                'difficulty': 1,
                                'ifcomplex': False,
                                'postfix': ' &ywith piping'},
                  'ModRazored': {'complexity': 1,
                                 'difficulty': 1,
                                 'ifcomplex': True,
                                 'prefix': '&Yserra&Rt&Yed&y '},
                  'ModScoped': {'complexity': 1,
                                'difficulty': 1,
                                'ifcomplex': False,
                                'prefix': '&yscoped '},
                  'ModSharp': {'complexity': 1,
                               'difficulty': 1,
                               'ifcomplex': True,
                               'prefix': 'sharp '},
                  'ModSpringLoaded': {'complexity': 1,
                                      'difficulty': 1,
                                      'ifcomplex': False,
                                      'prefix': 'spring-loaded '},
                  'ModSturdy': {'complexity': 0,
                                'difficulty': 0,
                                'ifcomplex': False,
                                'prefix': 'sturdy '},
                  'ModWired': {'complexity': 0,
                               'difficulty': 1,
                               'ifcomplex': True,
                               'prefix': '&cwired &y'}}

# This could be loaded from Factions.xml eventually, but for simplicity I'm putting it here for now.
FACTION_ID_TO_NAME = {
    'Antelopes': 'antelopes',
    'Apes': 'apes',
    'Arachnids': 'arachnids',
    'Baboons': 'baboons',
    'Baetyls': 'baetyls',
    'Barathrumites': 'Barathrumites',
    'Bears': 'bears',
    'Birds': 'birds',
    'Cannibals': 'cannibals',
    'Cats': 'cats',
    'Consortium': 'Consortium of Phyta',
    'Crabs': 'crabs',
    'Cragmensch': 'cragmensch',
    'Daughters': 'Daughters of Exile',
    'Dogs': 'dogs',
    'Dromad': 'dromad merchants',
    'Equines': 'equines',
    'Ezra': 'villagers of Ezra',
    'Farmers': 'Farmers\' Guild',
    'Fish': 'fish',
    'Flowers': 'flowers',
    'Frogs': 'frogs',
    'Fungi': 'fungi',
    'Girsh': 'Girsh',
    'Glow Wights': 'Glow-Wights',
    'Goatfolk': 'goatfolk',
    'Hermits': 'hermits',
    'highly entropic beings': 'highly entropic beings',
    'Hindren': 'hindren of Bey Lah',
    'Insects': 'insects',
    'Issachari': 'Issachari tribe',
    'Joppa': 'villagers of Joppa',
    'Kyakukya': 'villagers of Kyakukya',
    'Mamon': 'Children of Mamon',
    'Mechanimists': 'Mechanimists',
    'Merchants': 'Merchants\' Guild',
    'Mollusks': 'mollusks',
    'Mopango': 'mopango',
    'Naphtaali': 'Naphtaali tribe',
    'Newly Sentient Beings': 'newly sentient beings',
    'Oozes': 'oozes',
    'Pariahs': 'pariahs',
    'Prey': 'grazing hedonists',
    'Resheph': 'Cult of the Coiled Lamb',
    'Robots': 'robots',
    'Roots': 'roots',
    'Seekers': 'Seekers of the Sightless Way',
    'Snapjaws': 'snapjaws',
    'Strangers': 'mysterious strangers',
    'Succulents': 'succulents',
    'Swine': 'swine',
    'Templar': 'Putus Templar',
    'Tortoises': 'tortoises',
    'Trees': 'trees',
    'Trolls': 'trolls',
    'Unshelled Reptiles': 'unshelled reptiles',
    'Urchins': 'urchins',
    'Vines': 'vines',
    'Wardens': 'Fellowship of Wardens',
    'Water': 'water barons',
    'Winged Mammals': 'winged mammals',
    'Worms': 'worms'
}

CYBERNETICS_HARDCODED_INFIXES = {
    "CyberneticsMedassistModule": "{{c|Current loadout:}}{{y| no injectors}}"
}

CYBERNETICS_HARDCODED_POSTFIXES = {
    "CyberneticsAnomalyFumigator":
        "Compute power on the local lattice increases this item's effectiveness.",
    "CyberneticsCommunicationsInterlock":
        "Compute power on the local lattice increases this item's effectiveness.",
    "CyberneticsCustomVisage": "+300 reputation with <chosen faction>",
    "CyberneticsHighFidelityMatterRecompositer":
        "Compute power on the local lattice reduces this item's cooldown.",
    "CyberneticsInflatableAxons":
        "Compute power on the local lattice increases this item's effectiveness.",
    "CyberneticsMatterRecompositer":
        "Compute power on the local lattice reduces this item's cooldown.",
    "CyberneticsNocturnalApex":
        "Compute power on the local lattice increases this item's effectiveness.",
    "CyberneticsOnboardRecoilerTeleporter":
        "Compute power on the local lattice reduces this item's cooldown.",
    "CyberneticsCathedraBlackOpal":
        "Compute power on the local lattice increases this item's effectiveness.",
    "CyberneticsCathedraRuby":
        "Compute power on the local lattice increases this item's effectiveness.",
    "CyberneticsCathedraSapphire":
        "Compute power on the local lattice increases this item's effectiveness.",
    "CyberneticsCathedraWhiteOpal":
        "Compute power on the local lattice increases this item's effectiveness.",
    "CyberneticsPenetratingRadar":
        "Compute power on the local lattice increases this item's range.",
    "CyberneticsStasisProjector":
        "Compute power on the local lattice increases this item's effectiveness."
}

HARDCODED_CHARGE_USE = {
    'Displacer Bracelet': 1,
    'Neuro Animator': 5000,
    'Night-vision Goggles': 1,
    'Ninefold Boots': 250,
    'Stopsvaalinn': 500,
}
CHARGE_USE_REASONS = {
    'Displacer Bracelet': 'SpatialTransposer',
    'Neuro Animator': 'Object Animation',
    'Night-vision Goggles': 'Night Vision',
    'Ninefold Boots': 'Accelerative Teleporter',
    'Stopsvaalinn': 'ForceEmitter',
}

QUD_COLORS = {'r': (166, 74, 46),  # dark red
              'R': (215, 66, 0),  # bright red
              'w': (152, 135, 95),  # brown
              'W': (207, 192, 65),  # yellow
              'c': (64, 164, 185),  # dark cyan
              'C': (119, 191, 207),  # bright cyan
              'b': (0, 72, 189),  # dark blue
              'B': (0, 150, 255),  # bright blue
              'g': (0, 148, 3),  # dark green
              'G': (0, 196, 32),  # bright green
              'm': (177, 84, 207),  # dark magenta
              'M': (218, 91, 214),  # bright magenta
              'y': (177, 201, 195),  # bright grey
              'Y': (255, 255, 255),  # white
              'k': (15, 59, 58),  # black
              'K': (21, 83, 82),  # dark grey
              'o': (241, 95, 34),
              'O': (233, 159, 16),
              'transparent': (15, 64, 63, 0),
              }

QUD_VIRIDIAN = (15, 64, 63, 255)

LIQUID_COLORS = {'acid': '&G^g',
                 'algae': '&g^C',
                 'asphalt': '&k^K',
                 'blood': '&r^k',
                 'brainbrine': '&g^W',
                 'cider': '&w^r',
                 'cloning': '&M^Y',
                 'convalessence': '&Y^C',
                 'gel': '&y^Y',
                 'goo': '&Y^G',
                 'honey': '&w^W',
                 'ink': '&y^k',
                 'lava': '&W^R',
                 'neutronflux': '&Y^y',
                 'oil': '&Y^k',
                 'ooze': '&y^k',
                 'proteangunk': '&c^C',
                 'putrid': '&g^K',
                 'salt': '&Y^y',
                 'sap': '&W^Y',
                 'slime': '&w^g',
                 'sludge': '&Y^w',
                 'sunslag': '&Y^W',
                 'water': '&b^B',
                 'wax': '&y^Y',
                 'wine': '&m^r'
                 }

STAT_DISPLAY_NAMES = {'AcidResistance': 'acid resistance',
                      'ColdResistance': 'cold resistance',
                      'ElectricResistance': 'electric resistance',
                      'HeatResistance': 'heat resistance',
                      'Hitpoints': 'hit points',
                      'MoveSpeed': 'move speed',
                      'Speed': 'quickness'}

# The following includes all descending from IActivePart, which defines the IsEMPSensitive field.
# This list is accurate as of patch 202.79. There are also a few more parts that are special cases.
EMPSENSITIVE_PARTS = {'AccelerativeTeleporter': {'default': True},
                      'ActiveLightSource': {'default': False},
                      'AddsMutationOnEquip': {'default': False},
                      'AddsRep': {'default': False},
                      'AdjustSpecialEffectChances': {'default': True},
                      'AilingQuickness': {'default': False},
                      'AloePorta': {'default': False},
                      'AmbientCollector': {'default': True},
                      'AnimateObject': {'default': True},
                      'ArtifactDetection': {'default': False},
                      'ArtificialIntelligence': {'default': True},
                      'AutomatedExternalDefibrillator': {'default': True},
                      'Banner': {'default': False},
                      'Bed': {'default': False},
                      'BioAmmoLoader': {'default': False},
                      'BleedingOnHit': {'default': False},
                      'BootSequence': {'default': True},
                      'BroadcastPowerReceiver': {'default': True},
                      'BroadcastPowerTransmitter': {'default': True},
                      'BurnMe': {'default': False},
                      'Campfire': {'default': False},
                      'CannotBeInfluenced': {'default': False},
                      'Capacitor': {'default': True},
                      'CardiacArrestOnHit': {'default': False},
                      'CatacombsExitTeleporter': {'default': True},
                      'Chair': {'default': False},
                      'ChargeSink': {'default': True},
                      'Circuitry': {'default': True},
                      'Clockwork': {'default': False},
                      'CompanionCapacity': {'default': False},
                      'ComputeNode': {'default': True},
                      'CrossFlameOnStep': {'default': False},
                      'Cursed': {'default': False},
                      'CyberneticsAutomatedInternalDefibrillator': {'default': True},
                      'CyberneticsBiodynamicPowerPlant': {'default': True},
                      'CyberneticsEffectSuppressor': {'default': False},
                      'CyberneticsMedassistModule': {'default': True},
                      'CyberneticsMicromanipulatorArray': {'default': True},
                      'CyberneticsOnboardRecoilerImprinting': {'default': True},
                      'CyberneticsOnboardRecoilerTeleporter': {'default': True},
                      'CyberneticsPenetratingRadar': {'default': True},
                      'DamageContents': {'default': True},
                      'DecoyHologramEmitter': {'default': True},
                      'DeploymentMaintainer': {'default': True},
                      'DepositCorpses': {'default': False},
                      'DestroyMe': {'default': False},
                      'DiggingTool': {'default': False},
                      'DischargeOnHit': {'default': False},
                      'DischargeOnStep': {'default': False},
                      'DismemberAdjacentHostiles': {'default': True},
                      'Displacement': {'default': False},
                      'Displacer': {'default': True},
                      'Drill': {'default': True},
                      'DrinkMagnifier': {'default': False},
                      'ElectricalDischargeLoader': {'default': True},
                      'ElectricalPowerTransmission': {'default': True},
                      'ElementalDamage': {'default': False},
                      'EmergencyTeleporter': {'default': True},
                      'EmitGasOnHit': {'default': False},
                      'Enclosing': {'default': False},
                      'EnergyAmmoLoader': {'default': True},
                      'EnergyCell': {'default': True},
                      'EnergyCellSocket': {'default': True},
                      'Engulfing': {'default': False},
                      'EquipCharge': {'default': False},
                      'EquipIntProperties': {'default': False},
                      'EquipStatBoost': {'default': False},
                      'FabricateFromSelf': {'default': False},
                      'Fan': {'default': True},
                      'FeelingOnTarget': {'default': False},
                      'FireSuppressionSystem': {'default': True},
                      'FlareCompensation': {'default': False},
                      'Flywheel': {'default': False},
                      'FoliageCamouflage': {'default': False},
                      'FollowersGetTeleport': {'default': True},
                      'FoodProcessor': {'default': True},
                      'ForceEmitter': {'default': True},
                      'ForceProjector': {'default': True},
                      'FugueOnStep': {'default': False},
                      'FungalFortitude': {'default': False},
                      'FusionReactor': {'default': True},
                      'Gaslight': {'default': True},
                      'GasTumbler': {'default': True},
                      'GenericPowerTransmission': {'default': True},
                      'GenericTerminal': {'default': True},
                      'GlimmerAlteration': {'default': True},
                      'GrandfatherHorn': {'default': False},
                      'GritGateMainframeTerminal': {'default': True},
                      'GroundOnHit': {'default': True},
                      'HighBitBonus': {'default': False},
                      'HologramMaterialPrimary': {'default': True},
                      'HUD': {'default': True},
                      'HydraulicPowerTransmission': {'default': False},
                      'HydroTurbine': {'default': True},
                      'InductionCharger': {'default': True},
                      'InductionChargeReceiver': {'default': True},
                      'IntegralRecharger': {'default': True},
                      'IntegratedPowerSystems': {'default': True},
                      'IntPropertyChanger': {'default': True},
                      'ItemElements': {'default': False},
                      'LatchesOn': {'default': False},
                      'LeaksFluid': {'default': False},
                      'LifeSaver': {'default': True},
                      'LiquidAmmoLoader': {'default': False},
                      'LiquidFueledEnergyCell': {'default': True},
                      'LiquidFueledPowerPlant': {'default': False},
                      'LiquidProducer': {'default': False},
                      'LiquidPump': {'default': True},
                      'LiquidRepellent': {'default': False},
                      'LowStatBooster': {'default': True},
                      'MagazineAmmoLoader': {'default': False},
                      'MechanicalPowerTransmission': {'default': False},
                      'MechanicalWings': {'default': False},
                      'MentalScreen': {'default': True},
                      'Mill': {'default': True},
                      'MissilePerformance': {'default': False},
                      'ModAirfoil': {'default': False},
                      'ModAntiGravity': {'default': True},
                      'ModBeamsplitter': {'default': False},
                      'ModBeetlehost': {'default': True},
                      'ModBlinkEscape': {'default': True},
                      'ModCleated': {'default': False},
                      'ModColossal': {'default': False},
                      'ModCoProcessor': {'default': True},
                      'ModCounterweighted': {'default': False},
                      'ModDesecrated': {'default': False},
                      'ModDisguise': {'default': False},
                      'ModDisplacer': {'default': True},
                      'ModDrumLoaded': {'default': False},
                      'ModElectrified': {'default': True},
                      'ModEngraved': {'default': False},
                      'ModExtradimensional': {'default': False},
                      'ModFactionSlayer': {'default': False},
                      'ModFatecaller': {'default': False},
                      'ModFeathered': {'default': False},
                      'ModFeatherweight': {'default': False},
                      'ModFilters': {'default': False},
                      'ModFlaming': {'default': True},
                      'ModFlareCompensating': {'default': True},
                      'ModFlexiweaved': {'default': False},
                      'ModFreezing': {'default': True},
                      'ModGearbox': {'default': False},
                      'ModGesticulating': {'default': False},
                      'ModGlassArmor': {'default': False},
                      'ModGlazed': {'default': False},
                      'ModHardened': {'default': False},
                      'ModHeatSeeking': {'default': False},
                      'ModHighCapacity': {'default': False},
                      'ModHorrifying': {'default': False},
                      'ModHUD': {'default': False},
                      'ModIlluminated': {'default': False},
                      'ModImprovedBerserk': {'default': False},
                      'ModImprovedBlock': {'default': False},
                      'ModImprovedBludgeon': {'default': False},
                      'ModImprovedHobble': {'default': False},
                      'ModImprovedWindmillStance': {'default': False},
                      'ModInduction': {'default': False},
                      'ModJacked': {'default': False},
                      'ModJewelEncrusted': {'default': False},
                      'ModLacquered': {'default': False},
                      'ModLanterned': {'default': False},
                      'ModLight': {'default': False},
                      'ModLiquidCooled': {'default': False},
                      'ModMagnetized': {'default': True},
                      'ModMasterwork': {'default': False},
                      'ModMercurial': {'default': True},
                      'ModMetallized': {'default': False},
                      'ModMetered': {'default': False},
                      'ModMighty': {'default': False},
                      'ModMorphogenetic': {'default': True},
                      'ModNanochelated': {'default': False},
                      'ModNanon': {'default': False},
                      'ModNav': {'default': True},
                      'ModNormalizing': {'default': False},
                      'ModOverloaded': {'default': True},
                      'ModPadded': {'default': False},
                      'ModPainted': {'default': False},
                      'ModPhaseConjugate': {'default': False},
                      'ModPhaseHarmonic': {'default': False},
                      'ModPiping': {'default': False},
                      'ModPolarized': {'default': False},
                      'ModPsionic': {'default': False},
                      'ModRadioPowered': {'default': False},
                      'ModRazored': {'default': False},
                      'ModRecycling': {'default': False},
                      'ModRefractive': {'default': False},
                      'ModReinforced': {'default': False},
                      'ModRelicFreezing': {'default': True},
                      'ModScaled': {'default': False},
                      'ModScoped': {'default': False},
                      'ModSerene': {'default': False},
                      'ModSharp': {'default': False},
                      'ModSirocco': {'default': False},
                      'ModSixFingered': {'default': False},
                      'ModSmart': {'default': False},
                      'ModSnailEncrusted': {'default': False},
                      'ModSpiked': {'default': False},
                      'ModSpringLoaded': {'default': False},
                      'ModSturdy': {'default': False},
                      'ModSuspensor': {'default': True},
                      'ModTimereaver': {'default': True},
                      'ModTransmuteOnHit': {'default': False},
                      'ModTwoFaced': {'default': False},
                      'ModVisored': {'default': False},
                      'ModWallSocket': {'default': False},
                      'ModWeightless': {'default': False},
                      'ModWired': {'default': False},
                      'ModWooly': {'default': False},
                      'MultiIntPropertyChanger': {'default': True},
                      'MultiNavigationBonus': {'default': True},
                      'NavigationBonus': {'default': True},
                      'NightSightInterpolators': {'default': True},
                      'NightVision': {'default': True},
                      'NoKnockdown': {'default': False},
                      'PartsGas': {'default': True},
                      'PetPhylactery': {'default': True},
                      'PointDefense': {'default': True},
                      'Pounder': {'default': False},
                      'PowerCord': {'default': True},
                      'PoweredFloating': {'default': True},
                      'PowerOutlet': {'default': True},
                      'PowerSwitch': {'default': False},
                      'ProgrammableRecoiler': {'default': True},
                      'PsychicMeridian': {'default': False},
                      'RadiusEventSender': {'default': True},
                      'RealityStabilization': {'default': True},
                      'RealityStabilizeOnHit': {'default': True},
                      'ReclamationCist': {'default': True},
                      'RecoilOnDeath': {'default': False},
                      'ReduceCooldowns': {'default': True},
                      'ReduceEnergyCosts': {'default': True},
                      'ReflectProjectiles': {'default': True},
                      'RemotePowerSwitch': {'default': True},
                      'RequiresPowerToEquip': {'default': True},
                      'RespondToEvent': {'default': True},
                      'RocketSkates': {'default': False},
                      'SapChargeOnHit': {'default': False},
                      'SaveModifier': {'default': False},
                      'SaveModifiers': {'default': False},
                      'SlipRing': {'default': False},
                      'SlottedCellCharger': {'default': True},
                      'Smartgun': {'default': True},
                      'SolarArray': {'default': True},
                      'Stopsvaalinn': {'default': True},
                      'StrideMason': {'default': True},
                      'StunOnHit': {'default': True},
                      'Suspensor': {'default': True},
                      'SwapOnHit': {'default': False},
                      'TattooGun': {'default': False},
                      'Teleporter': {'default': True},
                      'TeleporterPair': {'default': True},
                      'TemperatureAdjuster': {'default': True},
                      'TemplarPhylactery': {'default': True},
                      'ThermalAmp': {'default': True},
                      'Toolbox': {'default': True},
                      'UniversalCharger': {'default': True},
                      'UrbanCamouflage': {'default': False},
                      'VampiricWeapon': {'default': False},
                      'VibroWeapon': {'default': True},
                      'Waldopack': {'default': True},
                      'WaterRitualDiscount': {'default': False},
                      'WindTurbine': {'default': True},
                      'Windup': {'default': False},
                      'ZeroPointEnergyCollector': {'default': True},
                      'ZoneAdjust': {'default': True},
                      # Special cases (not descending from IActivePart):
                      'ConveyorBelt': {'default': True},
                      'ConveyorPad': {'default': True},
                      'CryochamberWall': {'default': True},
                      'CyberneticsNightVision': {'default': True},
                      'GeomagneticDisc': {'default': True},
                      'MagnetizedApplicator': {'default': True},
                      'Robot': {'default': True},
                      'Tinkering_Mine': {'default': True},
                      'WalltrapAcid': {'default': True},
                      'WalltrapClockworkBeetles': {'default': True},
                      'WalltrapCrabs': {'default': True},
                      'WalltrapFire': {'default': True},
                      'WalltrapGas': {'default': True},
                      'WalltrapShock': {'default': True}}

# The 'Butcherable' part can contain a population tables reference if it begins with an '@' symbol.
# One day, we could potentially replace this if we start loading data from PopulationTables.xml.
BUTCHERABLE_POPTABLES = {
    'Eyeless Crab Corpse': {
        'Eyeless Crab Legs': {
            'Number': 1,
            'Weight': 95
        },
        'EyelessCrabShell': {
            'Number': 1,
            'Weight': 5
        }
    },
    'Knollworm Corpse': {
        'Raw Worm Meat': {
            'Number': 1,
            'Weight': 98
        },
        'Knollworm Skull': {
            'Number': 1,
            'Weight': 2
        }
    },
    'Albino ape corpse': {
        'Albino Ape Heart': {
            'Number': 1,
            'Weight': 10
        },
        'Ape Fur Cloak': {
            'Number': 1,
            'Weight': 20
        },
        'Albino Ape Pelt': {
            'Number': 1,
            'Weight': 70
        }
    },
    'Ogre ape corpse': {
        'Ogre Ape Heart': {
            'Number': 1,
            'Weight': 30
        },
        'Ogre Ape Pelt': {
            'Number': 1,
            'Weight': 70
        }
    },
    'Salthopper Corpse': {
        'Salthopper Chip': {
            'Number': 1,
            'Weight': 85
        },
        'SalthopperMandible': {
            'Number': 1,
            'Weight': 15
        }
    },
    'Quartz Baboon Corpse': {
        'Quartzfur Hat': {
            'Number': 1,
            'Weight': 20
        },
        'Quartzfur Cloak': {
            'Number': 1,
            'Weight': 20
        },
        'Quartzfur Gloves': {
            'Number': 1,
            'Weight': 20
        }
    }
}
