name: Check dependencies and lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  Install-Deps-Lint-Code:
    runs-on: ubuntu-latest
    steps:
      - run: python -m pip install --user poetry
      - run: python -m poetry install
      - run: python -m flake8
      - run: python -m black --check --line-length 100 .
