name: Check dependencies and lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  Install-Deps-Lint-Code:
    runs-on: ubuntu-latest
    steps:
      - run: python3.10 -m pip install --user poetry
      - run: python3.10 -m poetry install --dev
      - run: python3.10 -m flake8
      - run: python3.10 -m black --check --line-length 100 .
