name: Check dependencies and lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  Install-Deps-Lint-Code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies using poetry
        run: |
          pip install poetry
          poetry install
      - name: Lint code with flake8
        run: poetry run flake8
      - name: Lint code with black
        run: poetry run black --check --line-length 100 .
