name: Install dependencies and lint
on:
  push:
  pull_request:
jobs:
  Install-Deps-Lint-Code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies using poetry
        run: |
          pip install poetry
          poetry install
      - name: Lint code with ruff
        uses: chartboost/ruff-action@v1
        with:
          src: "./hagadias"
          version: 0.0.261
